-- Create the 'station' table
CREATE TABLE nimbus.station (
    stn_id VARCHAR(255) NOT NULL PRIMARY KEY,
    lng FLOAT4,
    lat FLOAT4,
    stn_cd1 VARCHAR(255),
    ht FLOAT4,
    ht_pa FLOAT4,
    ht_ta FLOAT4,
    st_wd FLOAT4,
    st_rn FLOAT4,
    stn_cd2 VARCHAR(255),
    stn_nm_kor VARCHAR(255),
    stn_nm_eng VARCHAR(255),
    fct_cd VARCHAR(255),
    pnu_bjd VARCHAR(255),
    updated_date DATE,
    is_deleted BOOLEAN
);

-- Create the 'measurements' table
CREATE TABLE nimbus.station_measure_time (
    date_str VARCHAR NOT NULL,
    hour INT NOT NULL,
    stn_id VARCHAR(255),
    wind_direction FLOAT4,
    wind_speed FLOAT4,
    gust_direction FLOAT4,
    gust_speed FLOAT4,
    gust_time VARCHAR(255),
    ground_hpa FLOAT4,
    sealevel_hpa FLOAT4,
    temperature FLOAT4,
    humidity FLOAT4,
    rain FLOAT4,
    rain_day1 FLOAT4,
    rain_day2 FLOAT4,
    rain_strength FLOAT4,
    snow_3hours FLOAT4,
    snow_day FLOAT4,
    snow_cumul FLOAT4,
    weather_report VARCHAR(255),
    cloud_total FLOAT4,
    cloud_mid_ht FLOAT4,
    cloud_min_ht FLOAT4,
    cloud_type VARCHAR(255),
    visibility FLOAT4,
    sun VARCHAR(255),
    status_ground VARCHAR(255),
    temperature_ground FLOAT4,
    status_sealevel VARCHAR(255),
    wave FLOAT4,
    is_raining VARCHAR(255),
    PRIMARY KEY (date_str, hour, stn_id),
    FOREIGN KEY (stn_id) REFERENCES nimbus.station(stn_id)
);